name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLASK_APP: webserver.py


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout your repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v2


      # Run your web server
      - name: Start web server
        run: |
          python3 webserver.py