name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLASK_APP: app.py

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup virtual env, install dependencies
      - name: Create Go env
        run: |
          go mod init test-cicd
          go mod tidy
          go build api_driver.go -o app.exe
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      # Kill gunicorn server, if running already
      - name: Kill gunicorn
        run: pkill gunicorn || true

      # Run gunicorn server
      - name: Run API server
        run: |
         ./app.exe