# This is a basic workflow to help you get started with Actions
name: Build and Run Go Application on Raspberry Pi

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18  # Specify your desired Go version

      - name: Build Go Application
        run: go build -o myapp api_driver.go  # Replace 'main.go' with your Go application's entry file

      - name: Upload Go Application Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: ./myapp

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download Go Application Artifact
        uses: actions/download-artifact@v2
        with:
          name: myapp
          path: .

      - name: Make Go Application Executable
        run: chmod +x myapp

      - name: Run Go Application
        run: ./myapp