name: Deploy to Raspberry Pi

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout your repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v2

      # Kill the web server, if running already
      - name: Kill web server
        run: pkill python3 webserver.py || true

      # Run your web server
      - name: Start web server
        run: |
          source flask-env/bin/activate
          python3 webserver.py