# name: Deploy to Raspberry Pi

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# env:
#   FLASK_APP: app.py

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: self-hosted

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.18  # Specify your desired Go version

#       - name: Build the Go application
#         run: |
#           go mod init test-cicd
#           go mod tidy
#           go build -o app api_driver.go

#   deploy:
#     runs-on: self-hosted
#     needs: build
    
#     steps:
#       # Run gunicorn server
#       - name: Run API server
#         run: |
#           chmod +x app
#           ./app

# This is a basic workflow to help you get started with Actions
name: Build and Run Go Application on Raspberry Pi

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18  # Specify your desired Go version

      - name: Build Go Application
        run: go build -o myapp api_driver.go  # Replace 'main.go' with your Go application's entry file

      - name: Upload Go Application Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: ./myapp

  download-and-run:
    runs-on: self-hosted
    needs: build-and-upload

    steps:
      - name: Download Go Application Artifact
        uses: actions/download-artifact@v2
        with:
          name: myapp
          path: .

      - name: Make Go Application Executable
        run: chmod +x myapp

      - name: Run Go Application
        run: ./myapp
